mission:  
  start_pos: [29, 5]
  goal_pos: [59, 19]

global_planner:
  heightfield_folder_path: 'C:/Users/mario/OneDrive/Desktop/MASTER/SEGUNDO_CUATRI/ROBOTS_DE_CAMPO/TRABAJO/FieldRobots_RoboticMaster/simulation_data/heightfield'
  executed_folder_path: 'C:/Users/mario/OneDrive/Desktop/MASTER/SEGUNDO_CUATRI/ROBOTS_DE_CAMPO/TRABAJO/FieldRobots_RoboticMaster/simulation_data/execution_data'
  subdiv: 800

local_planner:
  lookahead_distance: 3

  pure_pursuit:
    kp_linear: 0.5
    kp_angular: 0.3

  pose_pid:
    kp_x: 0.5
    kp_y: 0.5
    kp_theta: 0.3

robot:
  max_linear_vel: 1.5
  max_angular_vel: 0.5
